
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef SENSOR_OBJDICT_H
#define SENSOR_OBJDICT_H

#include "../libs/dspic_CanFestival/CanFestival-3/include/data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 Sensor_Board_valueRangeTest (UNS8 typeValue, void * value);
const indextable * Sensor_Board_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data Sensor_Board_Data;
extern UNS32 Strain_Gauge1;		/* Mapped at index 0x2001, subindex 0x00*/
extern UNS32 Strain_Gauge2;		/* Mapped at index 0x2002, subindex 0x00*/
extern UNS32 Strain_Gauge3;		/* Mapped at index 0x2003, subindex 0x00*/
extern UNS32 Strain_Gauge4;		/* Mapped at index 0x2004, subindex 0x00*/
extern UNS32 _24V_ADC;		/* Mapped at index 0x3001, subindex 0x00*/

#endif // SENSOR_OBJDICT_H
