CanFestival: include/emcy.h File Reference
emcy.h File Reference
Declarations of the functions that manage EMCY (emergency) messages.
#include <applicfg.h>
#include "data.h"
Functions
UNS8 EMCY_setError (CO_Data *d, UNS16 errCode, UNS8 errRegMask, UNS16 addInfo)
Sets a new error with code errCode. Also sets corresponding bits in Error register (1001h)
void EMCY_errorRecovered (CO_Data *d, UNS16 errCode)
Indicates it has recovered from error errCode. Also clears corresponding bits in Error register (1001h)
void emergencyInit (CO_Data *d)
Start EMCY consumer and producer.
void emergencyStop (CO_Data *d)
Stop EMCY producer and consumer.
void proceedEMCY (CO_Data *d, Message *m)
This function is responsible to process an EMCY canopen-message.
Detailed Description
Declarations of the functions that manage EMCY (emergency) messages.
Author
Luis Jimenez
Date
Wed Sep 26 2007
Definition in file emcy.h.
Function Documentation
void EMCY_errorRecovered (CO_Data * d, UNS16 errCode)
Indicates it has recovered from error errCode. Also clears corresponding bits in Error register (1001h)
Parameters
*d Pointer on a CAN object data structure
errCode The error code
Deletes error errCode. Also clears corresponding bits in Error register (1001h)
Parameters
d
errCode Code of the error
errRegister Bits of Error register (1001h) to be set.
Returns
1 if error, 0 if successful
Definition at line 198 of file emcy.c.
References sendEMCY().
UNS8 EMCY_setError (CO_Data * d, UNS16 errCode, UNS8 errRegMask, UNS16 addInfo)
Sets a new error with code errCode. Also sets corresponding bits in Error register (1001h)
Parameters
*d Pointer on a CAN object data structure
errCode The error code
errRegMask
addInfo
Returns
Sets a new error with code errCode. Also sets corresponding bits in Error register (1001h)
Parameters
d
errCode Code of the error
errRegister Bits of Error register (1001h) to be set.
Returns
1 if error, 0 if successful
Definition at line 139 of file emcy.c.
References sendEMCY().
void emergencyInit (CO_Data * d)
Start EMCY consumer and producer.
Parameters
*d Pointer on a CAN object data structure
start the EMCY mangagement.
Parameters
d
Definition at line 75 of file emcy.c.
References OnNumberOfErrorsUpdate().
Referenced by switchCommunicationState().
void emergencyStop (CO_Data * d)
Stop EMCY producer and consumer.
Parameters
*d Pointer on a CAN object data structure
d
Definition at line 87 of file emcy.c.
Referenced by switchCommunicationState().
void proceedEMCY (CO_Data * d, Message * m)
This function is responsible to process an EMCY canopen-message.
Parameters
*d Pointer on a CAN object data structure
*m Pointer on the CAN-message which has to be analysed.
This function is responsible to process an EMCY canopen-message.
Parameters
d
m The CAN-message which has to be analysed.
Definition at line 239 of file emcy.c.
References Message::cob_id, and Message::len.
Referenced by canDispatch().