CanFestival: Heartbeat Object
Heartbeat Object
Communication Objects
Functions
void heartbeatInit (CO_Data *d)
Start heartbeat consumer and producer with respect to 0x1016 and 0x1017 object dictionary entries.
void heartbeatStop (CO_Data *d)
Stop heartbeat consumer and producer.
void ConsumerHeartbeatAlarm (CO_Data *d, UNS32 id)
void ProducerHeartbeatAlarm (CO_Data *d, UNS32 id)
UNS32 OnHeartbeatProducerUpdate (CO_Data *d, const indextable *unused_indextable, UNS8 unused_bSubindex)
Detailed Description
The heartbeat mechanism for a device is established through cyclically transmitting a message by a heartbeat producer. One or more devices in the network are aware of this heartbeat message. If the heartbeat cycle fails for the heartbeat producer the local application on the heartbeat consumer will be informed about that event.
Function Documentation
void ConsumerHeartbeatAlarm (CO_Data * d, UNS32 id)
The Consumer Timer Callback
Parameters
d
id
call heartbeat error with NodeId
Definition at line 67 of file lifegrd.c.
Referenced by heartbeatInit(), and proceedNODE_GUARD().
void heartbeatInit (CO_Data * d)
Start heartbeat consumer and producer with respect to 0x1016 and 0x1017 object dictionary entries.
Parameters
*d Pointer on a CAN object data structure
Definition at line 288 of file lifegrd.c.
References ConsumerHeartbeatAlarm(), OnHeartbeatProducerUpdate(), ProducerHeartbeatAlarm(), and SetAlarm().
Referenced by lifeGuardInit(), and OnHeartbeatProducerUpdate().
void heartbeatStop (CO_Data * d)
Stop heartbeat consumer and producer.
Parameters
*d Pointer on a CAN object data structure
Definition at line 338 of file lifegrd.c.
References DelAlarm().
Referenced by lifeGuardStop(), and OnHeartbeatProducerUpdate().
UNS32 OnHeartbeatProducerUpdate (CO_Data * d, const indextable * unused_indextable, UNS8 unused_bSubindex)
This is called when Index 0x1017 is updated.
Parameters
d
unused_indextable
unused_bSubindex
Returns
Definition at line 281 of file lifegrd.c.
References heartbeatInit(), and heartbeatStop().
Referenced by heartbeatInit().
void ProducerHeartbeatAlarm (CO_Data * d, UNS32 id)
The Producer Timer Callback
Parameters
d
id
Definition at line 173 of file lifegrd.c.
References Message::cob_id, Message::data, DelAlarm(), Message::len, and Message::rtr.
Referenced by heartbeatInit().