CanFestival: include/lifegrd.h File Reference
lifegrd.h File Reference
#include <applicfg.h>
#include "data.h"
Functions
void nodeguardInit (CO_Data *d)
Start node guarding with respect to 0x100C and 0x100D in the object dictionary.
void nodeguardStop (CO_Data *d)
Stop producing node guarding messages.
void lifeGuardInit (CO_Data *d)
Start the life guarding service (heartbeat/node guarding). This service handles NMT error control messages either by using heartbeats and/or by using node guarding messages (defined via the object dictionary)
void lifeGuardStop (CO_Data *d)
Stop the life guarding service (heartbeat/node guarding).
e_nodeState getNodeState (CO_Data *d, UNS8 nodeId)
To read the state of a node This can be used by the master after having sent a life guard request, of by any node if it is waiting for heartbeat.
void heartbeatInit (CO_Data *d)
Start heartbeat consumer and producer with respect to 0x1016 and 0x1017 object dictionary entries.
void heartbeatStop (CO_Data *d)
Stop heartbeat consumer and producer.
void proceedNODE_GUARD (CO_Data *d, Message *m)
This function is responsible to process a canopen-message which seams to be an NMT Error Control Messages. If a BootUp message is detected, it will return the nodeId of the Slave who booted up.
Detailed Description
Author
Markus WILDBOLZ
Date
Mon Oct 01 14:44:36 CEST 2012
Definition in file lifegrd.h.
Function Documentation
void lifeGuardInit (CO_Data * d)
Start the life guarding service (heartbeat/node guarding). This service handles NMT error control messages either by using heartbeats and/or by using node guarding messages (defined via the object dictionary)
Parameters
*d Pointer on a CAN object data structure
Definition at line 355 of file lifegrd.c.
References heartbeatInit(), and nodeguardInit().
Referenced by switchCommunicationState().
void lifeGuardStop (CO_Data * d)
Stop the life guarding service (heartbeat/node guarding).
Parameters
*d Pointer on a CAN object data structure
Definition at line 362 of file lifegrd.c.
References heartbeatStop(), and nodeguardStop().
Referenced by switchCommunicationState().