CanFestival: src/nmtSlave.c File Reference
nmtSlave.c File Reference
#include "nmtSlave.h"
#include "states.h"
#include "canfestival.h"
#include "sysdep.h"
Functions
void proceedNMTstateChange (CO_Data *d, Message *m)
Threat the reception of a NMT message from the master.
UNS8 slaveSendBootUp (CO_Data *d)
Transmit the boot-Up frame when the slave is moving from initialization state to pre_operational state.
Detailed Description
Author
Edouard TISSERANT and Francis DUPIN
Date
Tue Jun 5 08:50:53 2007
Definition in file nmtSlave.c.
Function Documentation
void proceedNMTstateChange (CO_Data * d, Message * m)
Threat the reception of a NMT message from the master.
put the slave in the state wanted by the master
Parameters
d
m
Definition at line 44 of file nmtSlave.c.
References getNodeId(), setNodeId(), and setState().
Referenced by canDispatch().
UNS8 slaveSendBootUp (CO_Data * d)
Transmit the boot-Up frame when the slave is moving from initialization state to pre_operational state.
Parameters
d
Returns
Definition at line 118 of file nmtSlave.c.
References Message::cob_id, Message::data, Message::len, and Message::rtr.
Referenced by switchCommunicationState().