CanFestival: src/states.c File Reference
states.c File Reference
#include "data.h"
#include "sysdep.h"
Functions
void switchCommunicationState (CO_Data *d, s_state_communication *newCommunicationState)
e_nodeState getState (CO_Data *d)
Returns the state of the node.
void canDispatch (CO_Data *d, Message *m)
Called by driver/app when receiving messages.
UNS8 setState (CO_Data *d, e_nodeState newState)
Change the state of the node.
UNS8 getNodeId (CO_Data *d)
Returns the nodId.
void setNodeId (CO_Data *d, UNS8 nodeId)
Define the node ID. Initialize the object dictionary.
void _initialisation (CO_Data *d)
Function that user app can overload.
void _preOperational (CO_Data *d)
Function that user app can overload.
void _operational (CO_Data *d)
Function that user app can overload.
void _stopped (CO_Data *d)
Function that user app can overload.
Detailed Description
Author
Edouard TISSERANT and Francis DUPIN
Date
Tue Jun 5 09:32:32 2007
Definition in file states.c.
Function Documentation
void canDispatch (CO_Data * d, Message * m)
Called by driver/app when receiving messages.
Parameters
d
m
Definition at line 63 of file states.c.
References Message::cob_id, proceedEMCY(), proceedNMTstateChange(), proceedNODE_GUARD(), proceedPDO(), proceedSDO(), and proceedSYNC().
void switchCommunicationState (CO_Data * d, s_state_communication * newCommunicationState)
Prototypes for internals functions
Parameters
d
newCommunicationState
d
newCommunicationState
Definition at line 138 of file states.c.
References emergencyInit(), emergencyStop(), lifeGuardInit(), lifeGuardStop(), PDOInit(), PDOStop(), resetSDO(), slaveSendBootUp(), startSYNC(), and stopSYNC().
Referenced by setState().