CanFestival: src/sync.c File Reference
sync.c File Reference
#include "data.h"
#include "sync.h"
#include "canfestival.h"
#include "sysdep.h"
Functions
void SyncAlarm (CO_Data *d, UNS32 id)
UNS32 OnCOB_ID_SyncUpdate (CO_Data *d, const indextable *unsused_indextable, UNS8 unsused_bSubindex)
void startSYNC (CO_Data *d)
void stopSYNC (CO_Data *d)
UNS8 sendSYNCMessage (CO_Data *d)
Transmit a SYNC message on CAN bus.
UNS8 sendSYNC (CO_Data *d)
Transmit a SYNC message and trigger sync TPDOs.
UNS8 proceedSYNC (CO_Data *d)
This function is called when the node is receiving a SYNC message (cob-id = 0x80).
Detailed Description
Author
Edouard TISSERANT and Francis DUPIN
Date
Tue Jun 5 09:32:32 2007
Definition in file sync.c.
Function Documentation
UNS32 OnCOB_ID_SyncUpdate (CO_Data * d, const indextable * unsused_indextable, UNS8 unsused_bSubindex)
This is called when Index 0x1005 is updated.
Parameters
d
unsused_indextable
unsused_bSubindex
Returns
Definition at line 76 of file sync.c.
References startSYNC().
Referenced by startSYNC().
UNS8 proceedSYNC (CO_Data * d)
This function is called when the node is receiving a SYNC message (cob-id = 0x80).
Parameters
d
m
Returns
Definition at line 166 of file sync.c.
References _sendPDOevent().
Referenced by canDispatch(), and sendSYNC().
UNS8 sendSYNC (CO_Data * d)
Transmit a SYNC message and trigger sync TPDOs.
Parameters
d
cob_id
Returns
Definition at line 150 of file sync.c.
References proceedSYNC(), and sendSYNCMessage().
Referenced by SyncAlarm().
UNS8 sendSYNCMessage (CO_Data * d)
Transmit a SYNC message on CAN bus.
Parameters
d
cob_id
Returns
Definition at line 128 of file sync.c.
References Message::cob_id, Message::len, and Message::rtr.
Referenced by sendSYNC().
void startSYNC (CO_Data * d)
Parameters
d
Definition at line 87 of file sync.c.
References OnCOB_ID_SyncUpdate(), SetAlarm(), stopSYNC(), and SyncAlarm().
Referenced by OnCOB_ID_SyncUpdate(), and switchCommunicationState().
void stopSYNC (CO_Data * d)
Parameters
d
Definition at line 112 of file sync.c.
References DelAlarm().
Referenced by startSYNC(), and switchCommunicationState().
void SyncAlarm (CO_Data * d, UNS32 id)
Parameters
d
id
Definition at line 62 of file sync.c.
References sendSYNC().
Referenced by startSYNC().