
/* File generated by gen_cfile.py. Should not be modified. */

#include "power_objdict.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS32 Strain_Gauge1 = 0x0;		/* Mapped at index 0x2001, subindex 0x00 */
UNS32 Strain_Gauge2 = 0x0;		/* Mapped at index 0x2002, subindex 0x00 */
UNS32 Strain_Gauge3 = 0x0;		/* Mapped at index 0x2003, subindex 0x00 */
UNS32 Strain_Gauge4 = 0x0;		/* Mapped at index 0x2004, subindex 0x00 */
UNS32 _24V_ADC = 0x0;		/* Mapped at index 0x3001, subindex 0x00 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 Power_Board_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 Power_Board_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 Power_Board_iam_a_slave = 1;

TIMER_HANDLE Power_Board_heartBeatTimers[3] = {TIMER_NONE,TIMER_NONE,TIMER_NONE};

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 Power_Board_obj1000 = 0x0;	/* 0 */
                    subindex Power_Board_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&Power_Board_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 Power_Board_obj1001 = 0x0;	/* 0 */
                    subindex Power_Board_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Power_Board_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 Power_Board_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 Power_Board_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    ODCallback_t Power_Board_Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    subindex Power_Board_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&Power_Board_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&Power_Board_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID */
                    UNS32 Power_Board_obj1005 = 0x0;   /* 0 */

/* index 0x1006 :   Communication / Cycle Period */
                    UNS32 Power_Board_obj1006 = 0x0;   /* 0 */

/* index 0x100C :   Guard Time */ 
                    UNS16 Power_Board_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 Power_Board_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID */
                    UNS32 Power_Board_obj1014 = 0x80 + 0x00;   /* 128 + NodeID */

/* index 0x1016 :   Consumer Heartbeat Time. */
                    UNS8 Power_Board_highestSubIndex_obj1016 = 3; /* number of subindex - 1*/
                    UNS32 Power_Board_obj1016[] = 
                    {
                      0x3E80100,	/* 65536256 */
                      0x3E80200,	/* 65536512 */
                      0x3E80400	/* 65537024 */
                    };
                    subindex Power_Board_Index1016[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Power_Board_highestSubIndex_obj1016 },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1016[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1016[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1016[2] }
                     };

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 Power_Board_obj1017 = 0x3E8;	/* 1000 */
                    ODCallback_t Power_Board_Index1017_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex Power_Board_Index1017[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Power_Board_obj1017 }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 Power_Board_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 Power_Board_obj1018_Vendor_ID = 0x3;	/* 3 */
                    UNS32 Power_Board_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 Power_Board_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 Power_Board_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex Power_Board_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Power_Board_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), (void*)&Power_Board_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), (void*)&Power_Board_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&Power_Board_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&Power_Board_obj1018_Serial_Number }
                     };

/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 Power_Board_highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS32 Power_Board_obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x603;	/* 1539 */
                    UNS32 Power_Board_obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x583;	/* 1411 */
                    subindex Power_Board_Index1200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Power_Board_highestSubIndex_obj1200 },
                       { RO, uint32, sizeof (UNS32), (void*)&Power_Board_obj1200_COB_ID_Client_to_Server_Receive_SDO },
                       { RO, uint32, sizeof (UNS32), (void*)&Power_Board_obj1200_COB_ID_Server_to_Client_Transmit_SDO }
                     };

/* index 0x1280 :   Client SDO 1 Parameter. */
                    UNS8 Power_Board_highestSubIndex_obj1280 = 3; /* number of subindex - 1*/
                    UNS32 Power_Board_obj1280_COB_ID_Client_to_Server_Transmit_SDO = 0x601;	/* 1537 */
                    UNS32 Power_Board_obj1280_COB_ID_Server_to_Client_Receive_SDO = 0x581;	/* 1409 */
                    UNS8 Power_Board_obj1280_Node_ID_of_the_SDO_Server = 0x1;	/* 1 */
                    subindex Power_Board_Index1280[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Power_Board_highestSubIndex_obj1280 },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1280_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1280_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Power_Board_obj1280_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 Power_Board_highestSubIndex_obj1400 = 6; /* number of subindex - 1*/
                    UNS32 Power_Board_obj1400_COB_ID_used_by_PDO = 0x181;	/* 385 */
                    UNS8 Power_Board_obj1400_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 Power_Board_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Power_Board_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Power_Board_obj1400_Event_Timer = 0x0;	/* 0 */
                    UNS8 Power_Board_obj1400_SYNC_start_value = 0x0;	/* 0 */
                    subindex Power_Board_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Power_Board_highestSubIndex_obj1400 },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1400_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Power_Board_obj1400_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Power_Board_obj1400_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Power_Board_obj1400_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Power_Board_obj1400_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Power_Board_obj1400_SYNC_start_value }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 Power_Board_highestSubIndex_obj1401 = 6; /* number of subindex - 1*/
                    UNS32 Power_Board_obj1401_COB_ID_used_by_PDO = 0x281;	/* 641 */
                    UNS8 Power_Board_obj1401_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 Power_Board_obj1401_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Power_Board_obj1401_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Power_Board_obj1401_Event_Timer = 0x0;	/* 0 */
                    UNS8 Power_Board_obj1401_SYNC_start_value = 0x0;	/* 0 */
                    subindex Power_Board_Index1401[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Power_Board_highestSubIndex_obj1401 },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1401_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Power_Board_obj1401_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Power_Board_obj1401_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Power_Board_obj1401_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Power_Board_obj1401_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Power_Board_obj1401_SYNC_start_value }
                     };

/* index 0x1402 :   Receive PDO 3 Parameter. */
                    UNS8 Power_Board_highestSubIndex_obj1402 = 6; /* number of subindex - 1*/
                    UNS32 Power_Board_obj1402_COB_ID_used_by_PDO = 0x400;	/* 1024 */
                    UNS8 Power_Board_obj1402_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Power_Board_obj1402_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Power_Board_obj1402_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Power_Board_obj1402_Event_Timer = 0x0;	/* 0 */
                    UNS8 Power_Board_obj1402_SYNC_start_value = 0x0;	/* 0 */
                    subindex Power_Board_Index1402[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Power_Board_highestSubIndex_obj1402 },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1402_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Power_Board_obj1402_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Power_Board_obj1402_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Power_Board_obj1402_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Power_Board_obj1402_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Power_Board_obj1402_SYNC_start_value }
                     };

/* index 0x1403 :   Receive PDO 4 Parameter. */
                    UNS8 Power_Board_highestSubIndex_obj1403 = 6; /* number of subindex - 1*/
                    UNS32 Power_Board_obj1403_COB_ID_used_by_PDO = 0x500;	/* 1280 */
                    UNS8 Power_Board_obj1403_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Power_Board_obj1403_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Power_Board_obj1403_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Power_Board_obj1403_Event_Timer = 0x0;	/* 0 */
                    UNS8 Power_Board_obj1403_SYNC_start_value = 0x0;	/* 0 */
                    subindex Power_Board_Index1403[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Power_Board_highestSubIndex_obj1403 },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1403_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Power_Board_obj1403_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Power_Board_obj1403_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Power_Board_obj1403_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Power_Board_obj1403_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Power_Board_obj1403_SYNC_start_value }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 Power_Board_highestSubIndex_obj1600 = 2; /* number of subindex - 1*/
                    UNS32 Power_Board_obj1600[] = 
                    {
                      0x20010020,	/* 536936480 */
                      0x20020020	/* 537002016 */
                    };
                    subindex Power_Board_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Power_Board_highestSubIndex_obj1600 },
                       { RW|TO_BE_SAVE, uint32, sizeof (UNS32), (void*)&Power_Board_obj1600[0] },
                       { RW|TO_BE_SAVE, uint32, sizeof (UNS32), (void*)&Power_Board_obj1600[1] }
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 Power_Board_highestSubIndex_obj1601 = 8; /* number of subindex - 1*/
                    UNS32 Power_Board_obj1601[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex Power_Board_Index1601[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Power_Board_highestSubIndex_obj1601 },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1601[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1601[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1601[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1601[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1601[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1601[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1601[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1601[7] }
                     };

/* index 0x1602 :   Receive PDO 3 Mapping. */
                    UNS8 Power_Board_highestSubIndex_obj1602 = 8; /* number of subindex - 1*/
                    UNS32 Power_Board_obj1602[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex Power_Board_Index1602[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Power_Board_highestSubIndex_obj1602 },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1602[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1602[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1602[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1602[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1602[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1602[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1602[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1602[7] }
                     };

/* index 0x1603 :   Receive PDO 4 Mapping. */
                    UNS8 Power_Board_highestSubIndex_obj1603 = 8; /* number of subindex - 1*/
                    UNS32 Power_Board_obj1603[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex Power_Board_Index1603[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Power_Board_highestSubIndex_obj1603 },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1603[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1603[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1603[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1603[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1603[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1603[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1603[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1603[7] }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 Power_Board_highestSubIndex_obj1800 = 6; /* number of subindex - 1*/
                    UNS32 Power_Board_obj1800_COB_ID_used_by_PDO = 0x183;	/* 387 */
                    UNS8 Power_Board_obj1800_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 Power_Board_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Power_Board_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Power_Board_obj1800_Event_Timer = 0x3E8;	/* 1000 */
                    UNS8 Power_Board_obj1800_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t Power_Board_Index1800_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex Power_Board_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Power_Board_highestSubIndex_obj1800 },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1800_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Power_Board_obj1800_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Power_Board_obj1800_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Power_Board_obj1800_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Power_Board_obj1800_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Power_Board_obj1800_SYNC_start_value }
                     };

/* index 0x1801 :   Transmit PDO 2 Parameter. */
                    UNS8 Power_Board_highestSubIndex_obj1801 = 6; /* number of subindex - 1*/
                    UNS32 Power_Board_obj1801_COB_ID_used_by_PDO = 0x280;	/* 640 */
                    UNS8 Power_Board_obj1801_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Power_Board_obj1801_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Power_Board_obj1801_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Power_Board_obj1801_Event_Timer = 0x0;	/* 0 */
                    UNS8 Power_Board_obj1801_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t Power_Board_Index1801_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex Power_Board_Index1801[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Power_Board_highestSubIndex_obj1801 },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1801_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Power_Board_obj1801_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Power_Board_obj1801_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Power_Board_obj1801_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Power_Board_obj1801_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Power_Board_obj1801_SYNC_start_value }
                     };

/* index 0x1802 :   Transmit PDO 3 Parameter. */
                    UNS8 Power_Board_highestSubIndex_obj1802 = 6; /* number of subindex - 1*/
                    UNS32 Power_Board_obj1802_COB_ID_used_by_PDO = 0x380;	/* 896 */
                    UNS8 Power_Board_obj1802_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Power_Board_obj1802_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Power_Board_obj1802_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Power_Board_obj1802_Event_Timer = 0x0;	/* 0 */
                    UNS8 Power_Board_obj1802_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t Power_Board_Index1802_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex Power_Board_Index1802[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Power_Board_highestSubIndex_obj1802 },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1802_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Power_Board_obj1802_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Power_Board_obj1802_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Power_Board_obj1802_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Power_Board_obj1802_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Power_Board_obj1802_SYNC_start_value }
                     };

/* index 0x1803 :   Transmit PDO 4 Parameter. */
                    UNS8 Power_Board_highestSubIndex_obj1803 = 6; /* number of subindex - 1*/
                    UNS32 Power_Board_obj1803_COB_ID_used_by_PDO = 0x480;	/* 1152 */
                    UNS8 Power_Board_obj1803_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Power_Board_obj1803_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Power_Board_obj1803_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Power_Board_obj1803_Event_Timer = 0x0;	/* 0 */
                    UNS8 Power_Board_obj1803_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t Power_Board_Index1803_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex Power_Board_Index1803[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Power_Board_highestSubIndex_obj1803 },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1803_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Power_Board_obj1803_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Power_Board_obj1803_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Power_Board_obj1803_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Power_Board_obj1803_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Power_Board_obj1803_SYNC_start_value }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 Power_Board_highestSubIndex_obj1A00 = 1; /* number of subindex - 1*/
                    UNS32 Power_Board_obj1A00[] = 
                    {
                      0x30010020	/* 805371936 */
                    };
                    subindex Power_Board_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Power_Board_highestSubIndex_obj1A00 },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1A00[0] }
                     };

/* index 0x1A01 :   Transmit PDO 2 Mapping. */
                    UNS8 Power_Board_highestSubIndex_obj1A01 = 8; /* number of subindex - 1*/
                    UNS32 Power_Board_obj1A01[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex Power_Board_Index1A01[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Power_Board_highestSubIndex_obj1A01 },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1A01[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1A01[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1A01[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1A01[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1A01[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1A01[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1A01[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1A01[7] }
                     };

/* index 0x1A02 :   Transmit PDO 3 Mapping. */
                    UNS8 Power_Board_highestSubIndex_obj1A02 = 8; /* number of subindex - 1*/
                    UNS32 Power_Board_obj1A02[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex Power_Board_Index1A02[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Power_Board_highestSubIndex_obj1A02 },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1A02[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1A02[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1A02[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1A02[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1A02[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1A02[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1A02[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1A02[7] }
                     };

/* index 0x1A03 :   Transmit PDO 4 Mapping. */
                    UNS8 Power_Board_highestSubIndex_obj1A03 = 8; /* number of subindex - 1*/
                    UNS32 Power_Board_obj1A03[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex Power_Board_Index1A03[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Power_Board_highestSubIndex_obj1A03 },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1A03[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1A03[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1A03[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1A03[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1A03[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1A03[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1A03[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&Power_Board_obj1A03[7] }
                     };

/* index 0x2001 :   Mapped variable Strain_Gauge1 */
                    subindex Power_Board_Index2001[] = 
                     {
                       { RW|TO_BE_SAVE, uint32, sizeof (UNS32), (void*)&Strain_Gauge1 }
                     };

/* index 0x2002 :   Mapped variable Strain_Gauge2 */
                    subindex Power_Board_Index2002[] = 
                     {
                       { RW|TO_BE_SAVE, uint32, sizeof (UNS32), (void*)&Strain_Gauge2 }
                     };

/* index 0x2003 :   Mapped variable Strain_Gauge3 */
                    subindex Power_Board_Index2003[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Strain_Gauge3 }
                     };

/* index 0x2004 :   Mapped variable Strain_Gauge4 */
                    subindex Power_Board_Index2004[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Strain_Gauge4 }
                     };

/* index 0x3001 :   Mapped variable 24V_ADC */
                    subindex Power_Board_Index3001[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&_24V_ADC }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable Power_Board_objdict[] = 
{
  { (subindex*)Power_Board_Index1000,sizeof(Power_Board_Index1000)/sizeof(Power_Board_Index1000[0]), 0x1000},
  { (subindex*)Power_Board_Index1001,sizeof(Power_Board_Index1001)/sizeof(Power_Board_Index1001[0]), 0x1001},
  { (subindex*)Power_Board_Index1016,sizeof(Power_Board_Index1016)/sizeof(Power_Board_Index1016[0]), 0x1016},
  { (subindex*)Power_Board_Index1017,sizeof(Power_Board_Index1017)/sizeof(Power_Board_Index1017[0]), 0x1017},
  { (subindex*)Power_Board_Index1018,sizeof(Power_Board_Index1018)/sizeof(Power_Board_Index1018[0]), 0x1018},
  { (subindex*)Power_Board_Index1200,sizeof(Power_Board_Index1200)/sizeof(Power_Board_Index1200[0]), 0x1200},
  { (subindex*)Power_Board_Index1280,sizeof(Power_Board_Index1280)/sizeof(Power_Board_Index1280[0]), 0x1280},
  { (subindex*)Power_Board_Index1400,sizeof(Power_Board_Index1400)/sizeof(Power_Board_Index1400[0]), 0x1400},
  { (subindex*)Power_Board_Index1401,sizeof(Power_Board_Index1401)/sizeof(Power_Board_Index1401[0]), 0x1401},
  { (subindex*)Power_Board_Index1402,sizeof(Power_Board_Index1402)/sizeof(Power_Board_Index1402[0]), 0x1402},
  { (subindex*)Power_Board_Index1403,sizeof(Power_Board_Index1403)/sizeof(Power_Board_Index1403[0]), 0x1403},
  { (subindex*)Power_Board_Index1600,sizeof(Power_Board_Index1600)/sizeof(Power_Board_Index1600[0]), 0x1600},
  { (subindex*)Power_Board_Index1601,sizeof(Power_Board_Index1601)/sizeof(Power_Board_Index1601[0]), 0x1601},
  { (subindex*)Power_Board_Index1602,sizeof(Power_Board_Index1602)/sizeof(Power_Board_Index1602[0]), 0x1602},
  { (subindex*)Power_Board_Index1603,sizeof(Power_Board_Index1603)/sizeof(Power_Board_Index1603[0]), 0x1603},
  { (subindex*)Power_Board_Index1800,sizeof(Power_Board_Index1800)/sizeof(Power_Board_Index1800[0]), 0x1800},
  { (subindex*)Power_Board_Index1801,sizeof(Power_Board_Index1801)/sizeof(Power_Board_Index1801[0]), 0x1801},
  { (subindex*)Power_Board_Index1802,sizeof(Power_Board_Index1802)/sizeof(Power_Board_Index1802[0]), 0x1802},
  { (subindex*)Power_Board_Index1803,sizeof(Power_Board_Index1803)/sizeof(Power_Board_Index1803[0]), 0x1803},
  { (subindex*)Power_Board_Index1A00,sizeof(Power_Board_Index1A00)/sizeof(Power_Board_Index1A00[0]), 0x1A00},
  { (subindex*)Power_Board_Index1A01,sizeof(Power_Board_Index1A01)/sizeof(Power_Board_Index1A01[0]), 0x1A01},
  { (subindex*)Power_Board_Index1A02,sizeof(Power_Board_Index1A02)/sizeof(Power_Board_Index1A02[0]), 0x1A02},
  { (subindex*)Power_Board_Index1A03,sizeof(Power_Board_Index1A03)/sizeof(Power_Board_Index1A03[0]), 0x1A03},
  { (subindex*)Power_Board_Index2001,sizeof(Power_Board_Index2001)/sizeof(Power_Board_Index2001[0]), 0x2001},
  { (subindex*)Power_Board_Index2002,sizeof(Power_Board_Index2002)/sizeof(Power_Board_Index2002[0]), 0x2002},
  { (subindex*)Power_Board_Index2003,sizeof(Power_Board_Index2003)/sizeof(Power_Board_Index2003[0]), 0x2003},
  { (subindex*)Power_Board_Index2004,sizeof(Power_Board_Index2004)/sizeof(Power_Board_Index2004[0]), 0x2004},
  { (subindex*)Power_Board_Index3001,sizeof(Power_Board_Index3001)/sizeof(Power_Board_Index3001[0]), 0x3001},
};

const indextable * Power_Board_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1016: i = 2;break;
		case 0x1017: i = 3;*callbacks = Power_Board_Index1017_callbacks; break;
		case 0x1018: i = 4;break;
		case 0x1200: i = 5;break;
		case 0x1280: i = 6;break;
		case 0x1400: i = 7;break;
		case 0x1401: i = 8;break;
		case 0x1402: i = 9;break;
		case 0x1403: i = 10;break;
		case 0x1600: i = 11;break;
		case 0x1601: i = 12;break;
		case 0x1602: i = 13;break;
		case 0x1603: i = 14;break;
		case 0x1800: i = 15;*callbacks = Power_Board_Index1800_callbacks; break;
		case 0x1801: i = 16;*callbacks = Power_Board_Index1801_callbacks; break;
		case 0x1802: i = 17;*callbacks = Power_Board_Index1802_callbacks; break;
		case 0x1803: i = 18;*callbacks = Power_Board_Index1803_callbacks; break;
		case 0x1A00: i = 19;break;
		case 0x1A01: i = 20;break;
		case 0x1A02: i = 21;break;
		case 0x1A03: i = 22;break;
		case 0x2001: i = 23;break;
		case 0x2002: i = 24;break;
		case 0x2003: i = 25;break;
		case 0x2004: i = 26;break;
		case 0x3001: i = 27;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &Power_Board_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status Power_Board_PDO_status[4] = {s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer};

const quick_index Power_Board_firstIndex = {
  5, /* SDO_SVR */
  6, /* SDO_CLT */
  7, /* PDO_RCV */
  11, /* PDO_RCV_MAP */
  15, /* PDO_TRS */
  19 /* PDO_TRS_MAP */
};

const quick_index Power_Board_lastIndex = {
  5, /* SDO_SVR */
  6, /* SDO_CLT */
  10, /* PDO_RCV */
  14, /* PDO_RCV_MAP */
  18, /* PDO_TRS */
  22 /* PDO_TRS_MAP */
};

const UNS16 Power_Board_ObjdictSize = sizeof(Power_Board_objdict)/sizeof(Power_Board_objdict[0]); 

CO_Data Power_Board_Data = CANOPEN_NODE_DATA_INITIALIZER(Power_Board);

